name: CI

on:
  push:
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest httpx pydantic-settings SQLAlchemy "psycopg[binary]" loguru ruff

      - name: Lint (ruff)
        run: ruff check .

      - name: Run unit tests only
        run: pytest -q -m "not integration"

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API image
        run: docker build -f docker/Dockerfile.api .

      - name: Build Worker image
        run: docker build -f docker/Dockerfile.worker .
